package com.cache.entity;

import java.util.Date;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_id
     *
     * @mbggenerated
     */
    private Integer eId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_portrait
     *
     * @mbggenerated
     */
    private String ePortrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_name
     *
     * @mbggenerated
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_pwd
     *
     * @mbggenerated
     */
    private String ePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_uname
     *
     * @mbggenerated
     */
    private String eUname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_birthday
     *
     * @mbggenerated
     */
    private Date eBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_level
     *
     * @mbggenerated
     */
    private Integer eLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_six
     *
     * @mbggenerated
     */
    private Integer eSix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_wages
     *
     * @mbggenerated
     */
    private Integer eWages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_hobby
     *
     * @mbggenerated
     */
    private String eHobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_deptId
     *
     * @mbggenerated
     */
    private Integer eDeptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.e_dept_id
     *
     * @mbggenerated
     */
    private Integer eDeptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_id
     *
     * @return the value of emp.e_id
     *
     * @mbggenerated
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_id
     *
     * @param eId the value for emp.e_id
     *
     * @mbggenerated
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_portrait
     *
     * @return the value of emp.e_portrait
     *
     * @mbggenerated
     */
    public String getePortrait() {
        return ePortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_portrait
     *
     * @param ePortrait the value for emp.e_portrait
     *
     * @mbggenerated
     */
    public void setePortrait(String ePortrait) {
        this.ePortrait = ePortrait == null ? null : ePortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_name
     *
     * @return the value of emp.e_name
     *
     * @mbggenerated
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_name
     *
     * @param eName the value for emp.e_name
     *
     * @mbggenerated
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_pwd
     *
     * @return the value of emp.e_pwd
     *
     * @mbggenerated
     */
    public String getePwd() {
        return ePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_pwd
     *
     * @param ePwd the value for emp.e_pwd
     *
     * @mbggenerated
     */
    public void setePwd(String ePwd) {
        this.ePwd = ePwd == null ? null : ePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_uname
     *
     * @return the value of emp.e_uname
     *
     * @mbggenerated
     */
    public String geteUname() {
        return eUname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_uname
     *
     * @param eUname the value for emp.e_uname
     *
     * @mbggenerated
     */
    public void seteUname(String eUname) {
        this.eUname = eUname == null ? null : eUname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_birthday
     *
     * @return the value of emp.e_birthday
     *
     * @mbggenerated
     */
    public Date geteBirthday() {
        return eBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_birthday
     *
     * @param eBirthday the value for emp.e_birthday
     *
     * @mbggenerated
     */
    public void seteBirthday(Date eBirthday) {
        this.eBirthday = eBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_level
     *
     * @return the value of emp.e_level
     *
     * @mbggenerated
     */
    public Integer geteLevel() {
        return eLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_level
     *
     * @param eLevel the value for emp.e_level
     *
     * @mbggenerated
     */
    public void seteLevel(Integer eLevel) {
        this.eLevel = eLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_six
     *
     * @return the value of emp.e_six
     *
     * @mbggenerated
     */
    public Integer geteSix() {
        return eSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_six
     *
     * @param eSix the value for emp.e_six
     *
     * @mbggenerated
     */
    public void seteSix(Integer eSix) {
        this.eSix = eSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_wages
     *
     * @return the value of emp.e_wages
     *
     * @mbggenerated
     */
    public Integer geteWages() {
        return eWages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_wages
     *
     * @param eWages the value for emp.e_wages
     *
     * @mbggenerated
     */
    public void seteWages(Integer eWages) {
        this.eWages = eWages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_hobby
     *
     * @return the value of emp.e_hobby
     *
     * @mbggenerated
     */
    public String geteHobby() {
        return eHobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_hobby
     *
     * @param eHobby the value for emp.e_hobby
     *
     * @mbggenerated
     */
    public void seteHobby(String eHobby) {
        this.eHobby = eHobby == null ? null : eHobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_deptId
     *
     * @return the value of emp.e_deptId
     *
     * @mbggenerated
     */
    public Integer geteDeptid() {
        return eDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_deptId
     *
     * @param eDeptid the value for emp.e_deptId
     *
     * @mbggenerated
     */
    public void seteDeptid(Integer eDeptid) {
        this.eDeptid = eDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.e_dept_id
     *
     * @return the value of emp.e_dept_id
     *
     * @mbggenerated
     */
    public Integer geteDeptId() {
        return eDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.e_dept_id
     *
     * @param eDeptId the value for emp.e_dept_id
     *
     * @mbggenerated
     */
    public void seteDeptId(Integer eDeptId) {
        this.eDeptId = eDeptId;
    }
}